//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Domain.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Display {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Display() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Framework.Domain.Resource.Display", typeof(Display).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شارژ حساب.
        /// </summary>
        public static string AccountCharge {
            get {
                return ResourceManager.GetString("AccountCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات جزییات اکشن ها برای محاسبه قیمت.
        /// </summary>
        public static string ActionDetails {
            get {
                return ResourceManager.GetString("ActionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات تاریخچه اکشن.
        /// </summary>
        public static string ActionHistories {
            get {
                return ResourceManager.GetString("ActionHistories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه اکشن.
        /// </summary>
        public static string ActionPriceId {
            get {
                return ResourceManager.GetString("ActionPriceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات اشکن ها برای محاسبه قیمت.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع اکشن.
        /// </summary>
        public static string ActionTypeEnum {
            get {
                return ResourceManager.GetString("ActionTypeEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محاسبه قیمت درخواست.
        /// </summary>
        public static string CalculateRequestCostQuery {
            get {
                return ResourceManager.GetString("CalculateRequestCostQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شارژ حساب.
        /// </summary>
        public static string ChargeOrganizationStockCommand {
            get {
                return ResourceManager.GetString("ChargeOrganizationStockCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه قرارداد.
        /// </summary>
        public static string ContractId {
            get {
                return ResourceManager.GetString("ContractId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد حساب.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد اکشن قیمت.
        /// </summary>
        public static string CreateActionPriceCommand {
            get {
                return ResourceManager.GetString("CreateActionPriceCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ایجاد.
        /// </summary>
        public static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد محدودیت درخواست.
        /// </summary>
        public static string CreateLimitRequestCommand {
            get {
                return ResourceManager.GetString("CreateLimitRequestCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد تسهیلات.
        /// </summary>
        public static string CreateLoanCommand {
            get {
                return ResourceManager.GetString("CreateLoanCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد حساب.
        /// </summary>
        public static string CreateOrganizationStockCommand {
            get {
                return ResourceManager.GetString("CreateOrganizationStockCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف اکشن قیمت.
        /// </summary>
        public static string DeleteActionPriceCommand {
            get {
                return ResourceManager.GetString("DeleteActionPriceCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف محدودیت درخواست.
        /// </summary>
        public static string DeleteLimitRequestCommand {
            get {
                return ResourceManager.GetString("DeleteLimitRequestCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عمق.
        /// </summary>
        public static string Depth {
            get {
                return ResourceManager.GetString("Depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش اکشن قیمت.
        /// </summary>
        public static string EditActionPriceCommand {
            get {
                return ResourceManager.GetString("EditActionPriceCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش اطلاعات محدودیت درخواست.
        /// </summary>
        public static string EditLimitRequestCommand {
            get {
                return ResourceManager.GetString("EditLimitRequestCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش اطلاعات حساب.
        /// </summary>
        public static string EditOrganizationStockCommand {
            get {
                return ResourceManager.GetString("EditOrganizationStockCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ پایان.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام پدر.
        /// </summary>
        public static string FatherName {
            get {
                return ResourceManager.GetString("FatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه نوع رابطه ها.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی اول.
        /// </summary>
        public static string FirstNationalCode {
            get {
                return ResourceManager.GetString("FirstNationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه آگهی.
        /// </summary>
        public static string GazetteId {
            get {
                return ResourceManager.GetString("GazetteId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت اطلاعات اکشن.
        /// </summary>
        public static string GetActionPriceQuery {
            get {
                return ResourceManager.GetString("GetActionPriceQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت لیست اطلاعات اکشن ها.
        /// </summary>
        public static string GetAllActionPriceQuery {
            get {
                return ResourceManager.GetString("GetAllActionPriceQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت لیست اطلاعات قرارداد ها.
        /// </summary>
        public static string GetAllContractSidesQuery {
            get {
                return ResourceManager.GetString("GetAllContractSidesQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت لیست اطلاعات اشخاص حقوقی.
        /// </summary>
        public static string GetAllLegalPersonInformationQuery {
            get {
                return ResourceManager.GetString("GetAllLegalPersonInformationQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت عضوهای حقوقی.
        /// </summary>
        public static string GetAllLegalPersonMemberQuery {
            get {
                return ResourceManager.GetString("GetAllLegalPersonMemberQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت رابطه کد ملی ها.
        /// </summary>
        public static string GetAllNationalCodeRelationQuery {
            get {
                return ResourceManager.GetString("GetAllNationalCodeRelationQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت لیست حساب ها.
        /// </summary>
        public static string GetAllOrganizationStockQuery {
            get {
                return ResourceManager.GetString("GetAllOrganizationStockQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت لیست اطلاعات سوژه ها با شماره تلفن.
        /// </summary>
        public static string GetAllPersonByPhoneNumberQuery {
            get {
                return ResourceManager.GetString("GetAllPersonByPhoneNumberQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت اطلاعات افراد شرکت.
        /// </summary>
        public static string GetAllPersonCompanyQuery {
            get {
                return ResourceManager.GetString("GetAllPersonCompanyQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت لیست اطلاعات شخص حقیقی.
        /// </summary>
        public static string GetAllRealPersonInformationQuery {
            get {
                return ResourceManager.GetString("GetAllRealPersonInformationQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت لیست اطلاعات مربوط به روابط با توجه به سطح.
        /// </summary>
        public static string GetAllRealPersonRelationQuery {
            get {
                return ResourceManager.GetString("GetAllRealPersonRelationQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت اطلاعات نوع روابط.
        /// </summary>
        public static string GetAllRelativeTypeChildQuery {
            get {
                return ResourceManager.GetString("GetAllRelativeTypeChildQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت اطلاعات نوع روابط.
        /// </summary>
        public static string GetAllRelativeTypeParentQuery {
            get {
                return ResourceManager.GetString("GetAllRelativeTypeParentQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت اطلاعات قرارداد با کد ملی.
        /// </summary>
        public static string GetContractByIdQuery {
            get {
                return ResourceManager.GetString("GetContractByIdQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت اطلاعات قرارداد با شناسه قرارداد.
        /// </summary>
        public static string GetContractInfoQuery {
            get {
                return ResourceManager.GetString("GetContractInfoQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت رابطه خانوادگی.
        /// </summary>
        public static string GetFamilyRelationQuery {
            get {
                return ResourceManager.GetString("GetFamilyRelationQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت اطلاعات آگهی.
        /// </summary>
        public static string GetGazetteInformationQuery {
            get {
                return ResourceManager.GetString("GetGazetteInformationQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت اطلاعات افراد در آگهی.
        /// </summary>
        public static string GetGazettePersonInformationQuery {
            get {
                return ResourceManager.GetString("GetGazettePersonInformationQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت لیست اطلاعات اشخاص حقوقی در آگهی.
        /// </summary>
        public static string GetLegalPersonGazetteQuery {
            get {
                return ResourceManager.GetString("GetLegalPersonGazetteQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت اطلاعات شخص حقوقی.
        /// </summary>
        public static string GetLegalPersonInformationQuery {
            get {
                return ResourceManager.GetString("GetLegalPersonInformationQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت اطلاعات آخرین شخص حقوقی.
        /// </summary>
        public static string GetLegalPersonLastManagerQuery {
            get {
                return ResourceManager.GetString("GetLegalPersonLastManagerQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت شناسه ملی.
        /// </summary>
        public static string GetLegalPersonNationalCodeQuery {
            get {
                return ResourceManager.GetString("GetLegalPersonNationalCodeQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت اطلاعات کامل تسهیلات.
        /// </summary>
        public static string GetLoanFullInformationQuery {
            get {
                return ResourceManager.GetString("GetLoanFullInformationQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت اطلاعات شخص مرتبط با تسهیلات.
        /// </summary>
        public static string GetLoanPersonOfContractQuery {
            get {
                return ResourceManager.GetString("GetLoanPersonOfContractQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت اطلاعات حساب.
        /// </summary>
        public static string GetOrganizationStockQuery {
            get {
                return ResourceManager.GetString("GetOrganizationStockQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت اطلاعات آدرس.
        /// </summary>
        public static string GetPersonAddressQuery {
            get {
                return ResourceManager.GetString("GetPersonAddressQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت اطلاعات حساب شخص.
        /// </summary>
        public static string GetPersonBankAccountInformationQuery {
            get {
                return ResourceManager.GetString("GetPersonBankAccountInformationQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت نام شخص حقیقی .
        /// </summary>
        public static string GetPersonFullName {
            get {
                return ResourceManager.GetString("GetPersonFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت اطلاعات شخص مرتبط با تسهیلات.
        /// </summary>
        public static string GetPersonLoanInformationQuery {
            get {
                return ResourceManager.GetString("GetPersonLoanInformationQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت شماره تلفن های شخص.
        /// </summary>
        public static string GetPersonPhoneNumberQuery {
            get {
                return ResourceManager.GetString("GetPersonPhoneNumberQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت اطلاعات ارتباط خانوادگی.
        /// </summary>
        public static string GetRealPersonFamilyRelationQuery {
            get {
                return ResourceManager.GetString("GetRealPersonFamilyRelationQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت اطلاعات شخص حقیقی.
        /// </summary>
        public static string GetRealPersonInformationQuery {
            get {
                return ResourceManager.GetString("GetRealPersonInformationQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت کد ملی.
        /// </summary>
        public static string GetRealPersonNationalCodeQuery {
            get {
                return ResourceManager.GetString("GetRealPersonNationalCodeQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت اطلاعات روابط.
        /// </summary>
        public static string GetRelationQuery {
            get {
                return ResourceManager.GetString("GetRelationQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه اکشن.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال/غیرفعال بودن حساب.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن باقی مانده حساب به مبلغ حساب جدید.
        /// </summary>
        public static string IsAdded {
            get {
                return ResourceManager.GetString("IsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محدود/نامحدود بودن حساب.
        /// </summary>
        public static string IsUnLimit {
            get {
                return ResourceManager.GetString("IsUnLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه شخص حقوقی.
        /// </summary>
        public static string LegalPersonId {
            get {
                return ResourceManager.GetString("LegalPersonId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه ملی.
        /// </summary>
        public static string LegalPersonNationalCode {
            get {
                return ResourceManager.GetString("LegalPersonNationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سطح.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تا.
        /// </summary>
        public static string MaxDate {
            get {
                return ResourceManager.GetString("MaxDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر اعتبار منفی.
        /// </summary>
        public static string MaxNegativeCreadit {
            get {
                return ResourceManager.GetString("MaxNegativeCreadit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ از.
        /// </summary>
        public static string MinDate {
            get {
                return ResourceManager.GetString("MinDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام شخص.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی.
        /// </summary>
        public static string NationalCode {
            get {
                return ResourceManager.GetString("NationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آبجکت مربوط به پارامترهای رابطه کد ملی ها.
        /// </summary>
        public static string NationalCodeRelationArguments {
            get {
                return ResourceManager.GetString("NationalCodeRelationArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کدهای ملی.
        /// </summary>
        public static string NationalCodes {
            get {
                return ResourceManager.GetString("NationalCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش/عدم نمایش قیمت اکشن.
        /// </summary>
        public static string OnlyCalculateCommandPrice {
            get {
                return ResourceManager.GetString("OnlyCalculateCommandPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه سازمان.
        /// </summary>
        public static string OrganizationId {
            get {
                return ResourceManager.GetString("OrganizationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه های دسترسی.
        /// </summary>
        public static string PermissionsId {
            get {
                return ResourceManager.GetString("PermissionsId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه سوژه.
        /// </summary>
        public static string PersonId {
            get {
                return ResourceManager.GetString("PersonId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن ها.
        /// </summary>
        public static string PhoneNumbers {
            get {
                return ResourceManager.GetString("PhoneNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی.
        /// </summary>
        public static string RealPersonNationalCode {
            get {
                return ResourceManager.GetString("RealPersonNationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعات اخیر.
        /// </summary>
        public static string RecentHours {
            get {
                return ResourceManager.GetString("RecentHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد درخواست.
        /// </summary>
        public static string RequestCount {
            get {
                return ResourceManager.GetString("RequestCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه نقش.
        /// </summary>
        public static string RoleId {
            get {
                return ResourceManager.GetString("RoleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی دوم.
        /// </summary>
        public static string SecondNationalCode {
            get {
                return ResourceManager.GetString("SecondNationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ شروع.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آبونمان.
        /// </summary>
        public static string Subscription {
            get {
                return ResourceManager.GetString("Subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محاسبه آبونمان.
        /// </summary>
        public static string SubscriptionCommand {
            get {
                return ResourceManager.GetString("SubscriptionCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
    }
}
