//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Domain.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Status {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Status() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Framework.Domain.Resource.Status", typeof(Status).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان شارژ اکانت وجود ندارد.
        /// </summary>
        public static string CanNotCharge {
            get {
                return ResourceManager.GetString("CanNotCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجوز دسترسی به این سرویس‌ برای شما امکان‌پذیر نیست.
        /// </summary>
        public static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اکانت نامعتبر است.
        /// </summary>
        public static string InvalidAccount {
            get {
                return ResourceManager.GetString("InvalidAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات حساب ناقص است.
        /// </summary>
        public static string InvalidActionPrice {
            get {
                return ResourceManager.GetString("InvalidActionPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات واردشده معتبر نمی باشد.
        /// </summary>
        public static string InvalidModelState {
            get {
                return ResourceManager.GetString("InvalidModelState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی نامعتبر است.
        /// </summary>
        public static string InvalidNationalCode {
            get {
                return ResourceManager.GetString("InvalidNationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان ایجاد اکانت جدید وجود ندارد ، اکانت قبلی هنوز منقضی نشده است.
        /// </summary>
        public static string ItIsNotPossibleToCreateANewAccount {
            get {
                return ResourceManager.GetString("ItIsNotPossibleToCreateANewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی را وارد کنید.
        /// </summary>
        public static string NationalCode {
            get {
                return ResourceManager.GetString("NationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی 1 را وارد کنید.
        /// </summary>
        public static string NationalCode1 {
            get {
                return ResourceManager.GetString("NationalCode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی 2 را وارد کنید.
        /// </summary>
        public static string NationalCode2 {
            get {
                return ResourceManager.GetString("NationalCode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای کدملی حداکثر ده کاراکتر وارد کنید.
        /// </summary>
        public static string NationalCodeMinimumLength {
            get {
                return ResourceManager.GetString("NationalCodeMinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کدملی در سامانه یافت نشد.
        /// </summary>
        public static string NationalCodeNotFound {
            get {
                return ResourceManager.GetString("NationalCodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات یافت نشد.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محدودیت در دریافت اطلاعات.
        /// </summary>
        public static string OrganizationLimitRequest {
            get {
                return ResourceManager.GetString("OrganizationLimitRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجودی حساب کافی نیست.
        /// </summary>
        public static string StockNotEnough {
            get {
                return ResourceManager.GetString("StockNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در اعتبارسنجی کاربر.
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای ناشناخته.
        /// </summary>
        public static string UnkownError {
            get {
                return ResourceManager.GetString("UnkownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در ارتباط با پایگاه داده.
        /// </summary>
        public static string UseSqlServer {
            get {
                return ResourceManager.GetString("UseSqlServer", resourceCulture);
            }
        }
    }
}
